[versions]
kotlin = "2.4.0"
spring-boot = "4.1.0"
picocli = "4.7.7"
jmdns = "3.6.3"

[libraries]
spring-boot-bom            = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter        = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-test   = { module = "org.springframework.boot:spring-boot-starter-test" }
jackson-dataformat-xml     = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml" }
jackson-module-kotlin      = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
picocli                    = { module = "info.picocli:picocli", version.ref = "picocli" }
jmdns                      = { module = "org.jmdns:jmdns", version.ref = "jmdns" }
kotlin-reflect             = { module = "org.jetbrains.kotlin:kotlin-reflect" }

[plugins]
kotlin-jvm    = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot   = { id = "org.springframework.boot", version.ref = "spring-boot" }
